[server]
address = "127.0.0.1"
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#00c3ff"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F7"
textColor = "#1c2a31"
